### ISSUE TITLE
feat: add include-commit-links action input

### ISSUE THREAD

**Issue by FrancescoBonizzi** [ardalanamini/auto-changelog#135]
Hi and thanks for this very useful action!
I'd like just one thing: a config parameter to skip adding the whole commit link.

Example:

![image](https://user-images.githubusercontent.com/11348479/231401095-621dd65e-a974-41b3-980f-2f0cda9b5644.png)

As you can see after the commit name there a big link. 

Thanks.

**Comment by FrancescoBonizzi** [comment]
Hi @ardalanamini! I used a Github action to write the changelog to a file (.md) then I just opened it via GitHub website.

Currently the workflow file is this:

```
name: 'Generate release notes'
on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: 🚀 Nuove feature
            feature: 🚀 Nuove feature
            fix: 🐞 Bugfix
            perf: 📈 Migliorie di performance
            test: 👨‍🔬 Test
          default-commit-type: 👨🏻‍💻 Cose tecniche
          mention-authors: false
          include-compare: false
          semver: false

      - name: last-release-notes.md - Checkout repo
        uses: actions/checkout@v3
        
      - name: last-release-notes.md - Write
        uses: DamianReeves/write-file-action@master
        with:
          path: ./last-release-notes.md
          contents: | 
            ${{steps.changelog.outputs.changelog}}
          write-mode: overwrite 

      - name: last-release-notes.md - Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Aggiornate note ultima release'
```

And a part of the raw .md file output is this:

```
## 🚀 Nuove feature
* App - aggiunto switch "Tieni lo schermo attivo" nel popup con gli step della ricetta (https://github.com/drilldownsrl/tuduu/commit/d281736c6c1d29e936ad1bf8dbc1536e8cf39bf8)
* App - aggiunto pulsante "STAMPA" per stampare gli step di una ricetta (https://github.com/drilldownsrl/tuduu/commit/cf53636b98984518f563e91b57fc0a80bbebfc63)
* App - gli ingredienti iniziano sempre con la maiuscola per uniformare la tipografia (https://github.com/drilldownsrl/tuduu/commit/e8a556e3923707f7e3e8670ec0fd3730dc02c3eb)
```
