### ISSUE TITLE
feat: Add tag-pattern action input.

### ISSUE THREAD

**Issue by RobloxianDemo** [ardalanamini/auto-changelog#137]
Hey there! I really fancy this action and you have done a very good job on it!
I'd just fancy requesting and favor having this implemented into the action itself:
> **The ability to specify a `tag-pattern` to select and compare latest commits with rather than all commits in a specified tag.**

For example, in the specified image below, the specified tag-pattern should be `player` and it should retrieve the latest commits between it and the latest (similar) tag:
![image](https://user-images.githubusercontent.com/76854027/235267517-4d0722af-050a-4ac2-bf04-0fb4f15fae0e.png)

Where it'd appear similarly to this upon release, with the newly specified `tag-pattern` and its corresponding value of `player` only revealing the latest commit differences between the new and last tags with said pattern:
![image](https://user-images.githubusercontent.com/76854027/235267629-574424eb-87dc-40d2-9d02-b135544fbb6d.png)

Thank you again maintaining this wonderful GitHub Action!

**Comment by ardalanamini** [comment]
@RobloxianDemo Hi,
Thanks for submitting this feature request,
I'm happy to hear that you find this action useful.

To be clear, you don't want to reference all the different commits with the same message and to only reference the last one?

Also from the screenshot, I see the version bump commits are also added in the Changelog which is not intended 🤔

**Comment by ardalanamini** [comment]
Additionally, can you share the config you're using to generate your Changelog?

**Comment by RobloxianDemo** [comment]
Hey there!

No worries, and I'm glad to chip in with ideas! Preferably though, I'd favor having the last reference's commits being compared under the stated `tag-pattern` that was inputted, if not, it should stay as is (since my releases aren't  very semantic).

I just noticed that as well, and that sounds good! 👍 

As for the configuration file, here's the code for it:
```yaml
- name: Build the Changelog
  uses: ardalanamini/auto-changelog@v3
  id: build-changelog
  with:
    github-token: ${{ github.token }}
    commit-types: |
      Breaking: 🚨 Breaking Adjustments
      Build: 🧯 Build Adjustments
      Chore: 💄 New Chores
      CI: 💢 Continuous Integrations
      Dependency: 📖 Dependency Adjustments
      Documentation: 🌍 Documentation Adjustments
      Enhancement: 🚀 New Enhancements
      Feature: 🌟 New Features
      Fix: 🐞 Bug Fixes
      Other: 📂 Other Adjustments
      Patch: 🐞 Bug Patches
      Performance: 💊 Performance Improvements
      Refactor: 🐝 Refactored
      Revert: 🔙 Reverted
      Style: 🎨 Code Style Adjustments
      Test: ⛑ Tests
    default-commit-type: 📂 Other Adjustments
    # tag-pattern: ${{ env.TAG_NAME_LOWER }}
    include-compare: false
    semver: false
```

**Comment by ardalanamini** [comment]
I just released the `v4`, I think it also solves the issues you're facing 🤔 

As for the inputs you might want to change: (based on your screenshots)

```yaml
include-compare: true
release-name-prefix: "@robloxiandemo/player/"
semver: true
```

It should work properly with your case as far as I understood from the details, plus having a more optimized & readable Changelog, similar to [this](https://github.com/ardalanamini/auto-changelog/releases/tag/v4.0.0).
