### ISSUE TITLE
maybe a bug: in one repository it takes all commits

### ISSUE THREAD

**Issue by FrancescoBonizzi** [ardalanamini/auto-changelog#144]
Hi! I'm using your very useful action in a lot of my projects, but I have a problem in just one. Although the action is the same (Copy pasted) and although I create releases and tags in the same manner, in one repo it always **takes all commits** instead of just taking the commits from the last release.

## The GitHub action:

```
name: 📝 Generate release notes
on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: 🚀 Nuove feature
            feature: 🚀 Nuove feature
            fix: 🐞 Bugfix
            perf: 📈 Migliorie di performance
            test: 👨‍🔬 Test
            chore: 🧹 Pulizia codice
          default-commit-type: 👨🏻‍💻 Cose tecniche
          mention-authors: false
          include-compare: false
          semver: false
          include-commit-links: false
          include-pr-links: false

      - name: last-release-notes.md - Checkout repo
        uses: actions/checkout@v3
        
      - name: last-release-notes.md - Write
        uses: DamianReeves/write-file-action@master
        with:
          path: ./last-release-notes.md
          contents: | 
            ${{steps.changelog.outputs.changelog}}
          write-mode: overwrite 

      - name: last-release-notes.md - Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Aggiornate note ultima release'
```

The output:

![image](https://github.com/ardalanamini/auto-changelog/assets/11348479/b4a33ed1-c2c3-4be7-84bf-31517c9ecd50)

...and so on.

## My tags:
![image](https://github.com/ardalanamini/auto-changelog/assets/11348479/7d37a015-6c80-4fae-8665-b680265c7740)

I expected, as it is doing in my other repos, that it would take only the commits beginning from the v2.2.17.

---

Do you have any clue? Maybe is there some commit name that breaks it? Can I do something to help you investigate this?

Thanks.
