### ISSUE TITLE
bug: links are wrapped in code blocks

### ISSUE THREAD

**Issue by darksaid98** [ardalanamini/auto-changelog#220]
## Usage
I use the action to generate changelog for releases made to GitHub and other platforms like [Modrinth](https://modrinth.com/) (which also supports markdown changelogs). Obviously, GitHub auto-linking won't work off-site and thus I have it disabled.

## Current Behavior
When setting `use-github-autolink` to `false` all generated links are wrapped in \`\` codeblock ticks, causing said links to be unusable as they entire line is read as code.

See this in action here: <https://github.com/milkdrinkers/Enderchester/releases/tag/2.3.1-RC.4>.

## Expected Behavior
I assume the expected behavior is for the Markdown links to be inserted in the changelog without the \`\` codeblock ticks. This would result in the Markdown links `[]()` becoming parsed resulting in a readable and functional changelog output.

## Reproduction
```yaml
      # Generate changelog
      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type: Other Changes
          release-name: ${{ github.ref_name }}
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: true
          use-github-autolink: false
```

https://github.com/milkdrinkers/Enderchester/blob/2bcc81d56643ef08a2e83538f09cd96c0af31104/.github/workflows/deploy.yml#L71
