### ISSUE TITLE
bug: The prerelease output always returns false

### ISSUE THREAD

**Issue by manavtidhan** [ardalanamini/auto-changelog#59]
I have set semver: true and the release type is prerelease , However I am still getting the ${{ steps.changelog.outputs.prereleas}} value false. 

below is the code I have used.

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          mention-authors: true
          mention-new-contributors: true
          include-compare: true
          semver: true

      - name: Append the CHANGELOG.md
        shell: bash
        run: |
          echo  ${{ steps.changelog.outputs.prerelease }}

**Comment by ardalanamini** [comment]
@manavtidhan Thank you for the report, may I know what is the value passed to the `release-name` input?

**Comment by manavtidhan** [comment]
No value passed for release-name , the yml file is like below.

```
name: Changelog

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          mention-authors: true
          mention-new-contributors: true
          include-compare: true
          semver: true

      - name: Set Current Tag output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}          

      - name: Append the CHANGELOG.md
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        shell: bash
        run: echo  ${{ steps.changelog.outputs.prerelease }}
```
