### ISSUE TITLE
Change log grabs too many commit messages when tag is not latest

### ISSUE THREAD

**Issue by sdinay** [ardalanamini/auto-changelog#7]
Recreate:

1. Create and push some commits to your default (main) branch.
2. List your commits. Let's say your commits look like this:
  ```
  $ git log --pretty=oneline
  15027957951b64cf874c3557a0f3547bd83b3ff6 Merge branch 'experiment'
  a6b4c97498bd301d84096da251c98a07c7723e65 feat: Create write support
  0d52aaab4479697da7686c15f77a3d64d9165190 feat: One more thing
  6d52a271eda8725415634dd79daabbc4d9b6008e Merge branch 'experiment'
  0b7434d86859cc7b8c3d5e1dddfed66ff742fcbc feat: Add commit function
  9fceb02d0ae598e95dc970b74767f19372d61af8 feat: Update rakefile
 ```
3. Create a tag with an older commit than the most recent on in the main branch.
  ```
  git tag v1.2 0b7434d
  git push origin v1.2
  ```

The release github action is triggered:
```
name: Create Release

on:
  push:
    tags:
      - 'v*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
The `${{ steps.changelog.outputs.changelog }}` value will include all the commits:
```
Create write support
One more thing
Add commit function
Update rakefile
```
It should just checkout the tag and include only the changes between the previous tag and the current tag. Or if this is the first tag of the repository, it should include everything up to just the commit the tag refers to.
